#!/usr/bin/env bash
set -e
. "$AZGCLI_WORKDIR/modules/common"

cli_help_remove() {
    echo "
AzureGuard CLI - remove an interface. Please be careful, this will delete all peers.

Usage: azg [global options] interface remove [options]

Options:
  -n, --name        Name of the interface. It needs to match with the provided team
  -t, --team        Team to assign the interface to

Examples:
  azg interface remove -n MyNewInterface -t Prodigy
    "
    exit 1
}
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -n|--name)
            INTERFACENAME="$2"
            shift
            shift
        ;;
        -t|--team)
            TEAM="$2"
            shift
            shift
        ;;
        *)  cli_log "[ERROR] Invalid argument: $1"
            echo "Error: Invalid argument"
            shift
            cli_help_remove
        ;;
    esac
done

if [ -n "${INTERFACENAME}" ] && [ -n "${TEAM}" ]; then
    WIREGUARD_CONFIG="${WIREGUARD_PATH}/${INTERFACENAME}.conf"
    cli_log "[INFO] WireGuard config to remove: ${WIREGUARD_CONFIG}"
    if [ -f "${WIREGUARD_CONFIG}" ]; then
        if [ -d "${WIREGUARD_PATH}/${TEAM}/servers/${INTERFACENAME}" ]; then
            cli_log "[INFO] Stopping and disabling services ..."
            if pgrep systemd-journal > /dev/null 2>&1; then
                systemctl --quiet disable wg-quick@"${INTERFACENAME}"
                systemctl --quiet stop wg-quick@"${INTERFACENAME}"
                # wg-quick down "${INTERFACENAME}"
            else
                service wg-quick@"${INTERFACENAME}" disable
                service wg-quick@"${INTERFACENAME}" stop
                # wg-quick down "${INTERFACENAME}"
            fi
            
            cli_log "[INFO] Removing server directory ..."
            WIREGUARD_SERVER_PATH="${WIREGUARD_PATH}/${TEAM}/servers/${INTERFACENAME}"
            [[ -d "${WIREGUARD_SERVER_PATH}" ]] && rm -rf "${WIREGUARD_SERVER_PATH}"
            cli_log "[INFO] Removing config file ..."
            [[ -f "${WIREGUARD_CONFIG}" ]] && rm "${WIREGUARD_CONFIG}"
        else
            cli_log "[ERROR] Interface does not exist for this team"
            echo "Error: Interface does not exist for this team"
        fi
    else
        cli_log "[ERROR] Interface does not exist"
        echo "Error: Interface does not exist"
    fi
else
    cli_log "[ERROR] Missing required arguments"
    echo "Error: Missing required arguments"
    cli_help_remove
fi