#!/usr/bin/env bash
set -e

. "$AZGCLI_WORKDIR/modules/common"

cli_help_interface() {
    echo "
AzureGuard CLI

Usage: azg [global options] interface <operation>

Main operations:
  add       Add a wireguard interface
  remove    Remove a wireguard interface
  update    Update a wireguard interface
  show      Show wireguard interface details
  list      List wireguard interfaces
    "
    exit 1
}

[ -z "$1" ] && cli_help_interface

case "$1" in
    add)
        shift
        "$AZGCLI_WORKDIR/modules/interface/add" "$@"
    ;;
    remove)
        shift
        "$AZGCLI_WORKDIR/modules/interface/remove" "$@"
    ;;
    update)
        shift
        "$AZGCLI_WORKDIR/modules/interface/update" "$@"
    ;;
    show)
        shift
        "$AZGCLI_WORKDIR/modules/interface/show" "$@"
    ;;
    list)
        shift
        "$AZGCLI_WORKDIR/modules/interface/list" "$@"
    ;;
    *)
        cli_help_interface
    ;;
esac